/**
 * /init command — scaffold .pakalon/ directory with AI-generated planning files.
 *
 * When an `initialPrompt` is provided (or PAKALON_TOKEN / proxy available),
 * all planning files are generated via LLM rather than static stubs.
 * Falls back to high-quality stubs if LLM is unavailable.
 */
import fs from "fs";
import path from "path";
import { generateCompletion } from "@/ai/openrouter.js";
import { debugLog } from "@/utils/logger.js";
import { scaffoldProjectConfig } from "@/utils/project-config.js";

// Canonical file names per spec (.pakalon/ normal mode)
const INIT_FILES = [
  "plan.md",
  "task.md",       // spec: task.md (singular) for normal mode
  "user-stories.md",
  "context-management.md",
  "agents/skills.md",
  // API and DB design docs — read by Phase-3 Sub-agent 2 (backend framing)
  "API_reference.md",
  "Database_schema.md",
];

// ---------------------------------------------------------------------------
// Static fallback stubs
// ---------------------------------------------------------------------------

const PLAN_STUB = `# Plan

## Overview
_Generated by \`pakalon /init\`. Edit this file with your project plan._

## Goals
- [ ] Define primary objective
- [ ] Identify key deliverables

## Architecture
_Describe your tech stack and high-level architecture here._

## Timeline
_Add milestones and deadlines._
`;

const TASK_STUB = `# Tasks

## Phase 1: Setup
- [ ] Initialize project structure
- [ ] Configure environment

## Phase 2: Core
- [ ] Implement core features

## Phase 3: Polish
- [ ] Testing
- [ ] Documentation
`;

const USER_STORIES_STUB = `# User Stories

## US1 — Core User
**As a** user,
**I want to** ...
**So that** I can ...

**Acceptance Criteria:**
- [ ] AC1
- [ ] AC2
`;

const CONTEXT_MGMT_STUB = `# Context Management

## Token Budget
- Total window: TBD (set after model selection)
- Phase allocation: 70% conversation, 30% tools

## Key Files (priority context loading order)
1. plan.md
2. tasks.md
3. Source files (most recently modified)
`;

const SKILLS_STUB = `# Agent Skills

This file contains specialist agent skills for the project. These skills guide the AI in creating high-quality frontend and backend code.

---

## Available Skills

### 1. Frontend Design Skill

---

name: frontend-design

description: Create distinctive, production-grade frontend interfaces with high design quality. Use this skill when the user asks to build web components, pages, or applications. Generates creative, polished code that avoids generic AI aesthetics.

---

This skill guides creation of distinctive, production-grade frontend interfaces that avoid generic "AI slop" aesthetics. Implement real working code with exceptional attention to aesthetic details and creative choices.

The user provides frontend requirements: a component, page, application, or interface to build. They may include context about the purpose, audience, or technical constraints.

## Design Thinking

Before coding, understand the context and commit to a BOLD aesthetic direction:

- **Purpose**: What problem does this interface solve? Who uses it?
- **Tone**: Pick an extreme: brutally minimal, maximalist chaos, retro-futuristic, organic/natural, luxury/refined, playful/toy-like, editorial/magazine, brutalist/raw, art deco/geometric, soft/pastel, industrial/utilitarian, etc.
- **Constraints**: Technical requirements (framework, performance, accessibility).
- **Differentiation**: What makes this UNFORGETTABLE? What's the one thing someone will remember?

**CRITICAL**: Choose a clear conceptual direction and execute it with precision. Bold maximalism and refined minimalism both work - the key is intentionality, not intensity.

Then implement working code (HTML/CSS/JS, React, Vue, etc.) that is:

- Production-grade and functional
- Visually striking and memorable
- Cohesive with a clear aesthetic point-of-view
- Meticulously refined in every detail

## Frontend Aesthetics Guidelines

Focus on:

- **Typography**: Choose fonts that are beautiful, unique, and interesting. Avoid generic fonts like Arial and Inter; opt instead for distinctive choices that elevate the frontend's aesthetics; unexpected, characterful font choices. Pair a distinctive display font with a refined body font.

- **Color & Theme**: Commit to a cohesive aesthetic. Use CSS variables for consistency. Dominant colors with sharp accents outperform timid, evenly-distributed palettes.

- **Motion**: Use animations for effects and micro-interactions. Prioritize CSS-only solutions for HTML. Use Motion library for React when available. Focus on high-impact moments: one well-orchestrated page load with staggered reveals (animation-delay) creates more delight than scattered micro-interactions. Use scroll-triggering and hover states that surprise.

- **Spatial Composition**: Unexpected layouts. Asymmetry. Overlap. Diagonal flow. Grid-breaking elements. Generous negative space OR controlled density.

- **Backgrounds & Visual Details**: Create atmosphere and depth rather than defaulting to solid colors. Add contextual effects and textures that match the overall aesthetic. Apply creative forms like gradient meshes, noise textures, geometric patterns, layered transparencies, dramatic shadows, decorative borders, custom cursors, and grain overlays.

NEVER use generic AI-generated aesthetics like:

- Overused font families (Inter, Roboto, Arial, system fonts)
- Cliched color schemes (particularly purple gradients on white backgrounds)
- Predictable layouts and component patterns
- Cookie-cutter design that lacks context-specific character

Interpret creatively and make unexpected choices that feel genuinely designed for the context. No design should be the same. Vary between light and dark themes, different fonts, different aesthetics. NEVER converge on common choices across generations.

**IMPORTANT**: Match implementation complexity to the aesthetic vision. Maximalist designs need elaborate code with extensive animations and effects. Minimalist or refined designs need restraint, precision, and careful attention to spacing, typography, and subtle details. Elegance comes from executing the vision well.

---

### 2. Web Design Guidelines Skill

---

name: web-design-guidelines

description: Review UI code for Web Interface Guidelines compliance. Use when asked to "review my UI", "check accessibility", "audit design", "review UX", or "check my site against best practices".

## How It Works

1. Fetch the latest guidelines from the source URL below
2. Read the specified files (or prompt user for files/pattern)
3. Check against all rules in the fetched guidelines
4. Output findings in the terse file:line format

## Guidelines Source

Fetch fresh guidelines before each review:

\`
https://raw.githubusercontent.com/vercel-labs/web-interface-guidelines/main/command.md
\`

Use WebFetch to retrieve the latest rules. The fetched content contains all the rules and output format instructions.

## Usage

When a user provides a file or pattern argument:

1. Fetch guidelines from the source URL above
2. Read the specified files
3. Apply all rules from the fetched guidelines
4. Output findings using the format specified in the guidelines

If no files specified, ask the user which files to review.

---

### 3. React Best Practices Skill

---

name: react-best-practices

description: Apply React best practices for component architecture, state management, performance optimization, and modern hooks usage.

## Guidelines

- Use functional components with hooks
- Prefer composition over inheritance
- Keep components small and focused
- Use proper TypeScript types
- Implement proper error boundaries
- Optimize re-renders with useMemo/useCallback
- Follow React 19 patterns and best practices

---

### 4. Composition Patterns Skill

---

name: composition-patterns

description: Use advanced composition patterns for building flexible, reusable components. Includes compound components, render props, hooks composition, and state machines.

## Patterns

- Compound Components
- Render Props
- Custom Hooks
- State Machines (XState)
- Container/Presenter Pattern
- Provider Pattern

---

### 5. React Native Skills

---

name: react-native-skills

description: Build production-ready React Native applications with proper navigation, native modules, and platform-specific patterns.

## Skills

- React Native navigation
- Native module integration
- Platform-specific code
- Performance optimization
- Accessibility in mobile

---

## Recommended Activation Order

| Phase | Skill | When to Use |
|-------|-------|-------------|
| Phase 1 | Frontend Design | Initial UI requirements |
| Phase 1 | Web Design Guidelines | Design review |
| Phase 2 | React Best Practices | Component implementation |
| Phase 3 | Composition Patterns | Complex UI logic |
| Phase 3 | React Native | Mobile development |

## Collaboration Patterns

1. **Frontend Design** → identifies aesthetic direction
2. **Web Design Guidelines** → validates accessibility/compliance
3. **React Best Practices** → implements components
4. **Composition Patterns** → handles complex state
5. **React Native** → adapts for mobile

---

## Usage

Run \`pakalon /agents\` to configure specialist sub-agents with these skills.
`;

const STUBS: Record<string, string> = {
  "plan.md": PLAN_STUB,
  "task.md": TASK_STUB,
  "user-stories.md": USER_STORIES_STUB,
  "context-management.md": CONTEXT_MGMT_STUB,
  "agents/skills.md": SKILLS_STUB,
  "API_reference.md": `# API Reference

> Generated by Pakalon Phase-1 agent. Read by Phase-3 Sub-agent 2 (Backend Framing).

## Authentication

_Describe authentication flow (JWT, OAuth, session) here._

## Endpoints

### POST /api/auth/register
**Request:** \`{ email, password }\`
**Response:** \`{ userId, token }\`

_Add all endpoints here._

## Error Codes

| Code | Meaning |
|------|---------|
| 400  | Bad Request |
| 401  | Unauthorized |
| 404  | Not Found |
| 500  | Internal Server Error |
`,
  "Database_schema.md": `# Database Schema

> Generated by Pakalon Phase-1 agent. Read by Phase-3 Sub-agent 2 (Backend Framing).

## Overview

_Describe chosen database technology (PostgreSQL, SQLite, MongoDB, etc.) and ORM._

## Tables / Collections

### users
| Column     | Type         | Constraints           |
|------------|--------------|----------------------|
| id         | UUID         | PRIMARY KEY          |
| email      | VARCHAR(255) | UNIQUE, NOT NULL     |
| created_at | TIMESTAMP    | DEFAULT NOW()        |

_Add all tables/collections here._

## Relationships

_Describe foreign keys, indexes, and entity relationships._
`,
};

// ---------------------------------------------------------------------------
// AI generation prompts
// ---------------------------------------------------------------------------

type GenTarget =
  | "plan.md"
  | "task.md"
  | "user-stories.md"
  | "context-management.md"
  | "agents/skills.md"
  | "API_reference.md"
  | "Database_schema.md";

function buildPrompt(target: GenTarget, projectDescription: string): string {
  const prompts: Record<GenTarget, string> = {
    "plan.md": `You are a senior software architect. Generate a detailed project plan in Markdown for the following project.

Project description: ${projectDescription}

The plan MUST include:
1. ## Overview — 2–3 sentence summary
2. ## Goals — bulleted list of 5–8 specific, measurable goals
3. ## Architecture — tech stack, key components, data flow
4. ## Phases — 3–5 named phases with deliverables
5. ## Timeline — realistic milestones with estimated durations
6. ## Risks — top 3 risks and mitigations

Be specific and actionable. Output ONLY the Markdown document.`,

    "task.md": `You are a senior engineering lead. Create a comprehensive task breakdown in Markdown for the following project.

Project description: ${projectDescription}

Requirements:
- Group tasks into phases (Phase 1: Setup, Phase 2: Core, Phase 3: Testing, Phase 4: Launch)
- Each task: checkbox, short title, optional 1-line note
- Include at least 20 concrete tasks total
- Cover: infrastructure, backend, frontend, testing, CI/CD, docs, security

Output ONLY the Markdown document.`,

    "user-stories.md": `You are a product manager. Write detailed user stories in Markdown for the following project.

Project description: ${projectDescription}

Requirements:
- Write 8–12 user stories
- Format: ## US{N} — {Title}\\n**As a** {role},\\n**I want to** {action},\\n**So that** {benefit}
- Include Acceptance Criteria (3–5 checkboxes each)
- Cover primary user journeys, admin flows, error cases

Output ONLY the Markdown document.`,

    "context-management.md": `You are an AI systems engineer. Create a context management strategy in Markdown for an AI coding assistant working on the following project.

Project description: ${projectDescription}

Include:
1. ## Token Budget — window size, phase allocations, rolling window strategy
2. ## Key Files — priority list for context loading
3. ## Memory Strategy — what to keep in short-term vs long-term memory
4. ## Compression Rules — when to summarize older context
5. ## Tool Budget — max parallel tool calls, retry policy

Output ONLY the Markdown document.`,

    "agents/skills.md": `You are an AI orchestration architect. Define specialist agent skills in Markdown for the following project.

Project description: ${projectDescription}

Include:
1. ## Available Skills — list skills relevant to this specific project (6–10 skills)
2. For each skill: name, purpose, input/output, when to invoke
3. ## Recommended Activation Order — phase-by-phase skill activation chart
4. ## Collaboration Patterns — how agents hand off work to each other

Output ONLY the Markdown document.`,

    "API_reference.md": `You are a senior backend architect. Generate a complete API Reference document in Markdown for the following project.

Project description: ${projectDescription}

Requirements:
- List ALL REST/GraphQL/WebSocket endpoints the application will need
- For each endpoint: HTTP method, path, auth requirement, request body schema, response schema, error codes
- Include an ## Authentication section (JWT/OAuth/session — choose what fits best)
- Include a ## Error Codes table
- Be precise enough that a backend engineer can implement from this doc alone
- Phase-3 Sub-agent 2 (Backend Framing) will read this file as its primary spec

Output ONLY the Markdown document.`,

    "Database_schema.md": `You are a senior database architect. Generate a complete Database Schema document in Markdown for the following project.

Project description: ${projectDescription}

Requirements:
- Choose the most appropriate database technology (PostgreSQL / SQLite / MongoDB / etc.) and justify briefly
- Define ALL tables/collections with column names, types, constraints (PK, FK, UNIQUE, NOT NULL, DEFAULT)
- Include indexes for frequently queried columns
- Describe all foreign key relationships and join patterns
- Include a brief ER diagram described in text or Mermaid syntax
- Be precise enough that a backend engineer can write all migrations from this doc alone
- Phase-3 Sub-agent 2 (Backend Framing) will read this file as its primary DB spec

Output ONLY the Markdown document.`,
  };
  return prompts[target] ?? `Generate a detailed ${target} for: ${projectDescription}`;
}

// ---------------------------------------------------------------------------
// LLM generation with fallback
// ---------------------------------------------------------------------------

async function generateFileContent(
  target: string,
  projectDescription: string,
  model: string,
  authToken?: string,
): Promise<string> {
  const prompt = buildPrompt(target as GenTarget, projectDescription);
  try {
    const result = await generateCompletion({
      model,
      messages: [{ role: "user", content: prompt }],
      maxTokens: 2048,
      temperature: 0.7,
      authToken,
      // proxy mode auto-detected if no local key / PAKALON_USE_PROXY=1
    });
    return result.text.trim();
  } catch (err) {
    debugLog(`[init] LLM generation failed for ${target}: ${err}`);
    return STUBS[target] ?? `# ${target}\n\n_Generated by pakalon init_\n`;
  }
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

export async function cmdInit(cwd: string = process.cwd(), initialPrompt?: string): Promise<void> {
  const pakalonDir = path.join(cwd, ".pakalon");

  if (fs.existsSync(pakalonDir)) {
    console.log(`⚠ .pakalon/ already exists in ${cwd}`);
    console.log("Delete it first or use a different directory.");
    return;
  }

  console.log(`\n✦ Initializing Pakalon in ${cwd}...\n`);

  fs.mkdirSync(pakalonDir, { recursive: true });
  fs.mkdirSync(path.join(pakalonDir, "agents"), { recursive: true });

  const useAI = Boolean(
    initialPrompt ||
    process.env.PAKALON_TOKEN ||
    process.env.OPENROUTER_API_KEY ||
    process.env.PAKALON_USE_PROXY === "1",
  );

  const model = process.env.PAKALON_INIT_MODEL ?? "arcee-ai/trinity-large-preview:free";
  const authToken = process.env.PAKALON_TOKEN;
  const projectDescription = initialPrompt ?? path.basename(cwd);

  if (useAI) {
    console.log(`  Using AI to generate planning files (model: ${model})...\n`);
  }

  for (const file of INIT_FILES) {
    const filePath = path.join(pakalonDir, file);
    const dir = path.dirname(filePath);
    fs.mkdirSync(dir, { recursive: true });

    let content: string;
    if (useAI) {
      process.stdout.write(`  ⏳ Generating .pakalon/${file}...`);
      content = await generateFileContent(file, projectDescription, model, authToken);
      process.stdout.write(" ✓\n");
    } else {
      content = STUBS[file] ?? `# ${file}\n\n_Generated by pakalon init_\n`;
      console.log(`  ✓ Created .pakalon/${file}`);
    }

    fs.writeFileSync(filePath, content, "utf-8");
  }

  console.log("\n✓ .pakalon/ initialized successfully!");
  if (!useAI) {
    console.log("\nTip: Pass a project description to get AI-generated planning files:");
    console.log('  pakalon /init "E-commerce platform with React + Node.js"');
  }

  // Scaffold project config if none exists
  const cfgPath = scaffoldProjectConfig(cwd);
  if (cfgPath) {
    console.log(`  ✓ Created ${cfgPath.replace(cwd + path.sep, "")}`);
  }

  console.log("\nNext steps:");
  console.log("  1. Review .pakalon/plan.md and refine as needed");
  console.log("  2. Run `pakalon /agents` to configure specialist agents");
  console.log("  3. Start chatting — Pakalon uses these files as context");

  // Pre-populate ~/.config/pakalon/agents.json with default specialist agents
  // only if the file does not yet exist (never overwrite user customisations)
  const agentsConfigFile = path.join(
    process.env["HOME"] ?? process.env["USERPROFILE"] ?? "~",
    ".config",
    "pakalon",
    "agents.json",
  );
  if (!fs.existsSync(agentsConfigFile)) {
    const now = new Date().toISOString();
    const defaultAgents = [
      {
        id: "agent-frontend",
        name: "frontend",
        description: "React / Next.js / Tailwind UI specialist",
        systemPrompt:
          "You are an expert frontend engineer. Focus on React, Next.js, Tailwind CSS, and shadcn/ui. " +
          "Write accessible, responsive, and performant UI code. Prefer server components where possible.",
        color: "cyan",
        allowedTools: ["read_file", "write_file", "edit_file", "multi_edit_files", "list_dir", "bash", "glob_find", "grep_search"],
        createdAt: now,
      },
      {
        id: "agent-backend",
        name: "backend",
        description: "API / database / server-side specialist",
        systemPrompt:
          "You are an expert backend engineer. Focus on FastAPI, Node.js, PostgreSQL, Redis, and REST API design. " +
          "Write clean, typed, and well-tested server-side code with proper error handling.",
        color: "green",
        allowedTools: ["read_file", "write_file", "edit_file", "multi_edit_files", "list_dir", "bash", "glob_find", "grep_search"],
        createdAt: now,
      },
      {
        id: "agent-testing",
        name: "testing",
        description: "Test coverage and quality assurance specialist",
        systemPrompt:
          "You are an expert QA engineer. Write comprehensive unit, integration, and e2e tests. " +
          "Use Vitest for TypeScript, pytest for Python, and Playwright for browser automation.",
        color: "yellow",
        allowedTools: ["read_file", "write_file", "edit_file", "bash", "glob_find", "grep_search"],
        createdAt: now,
      },
      {
        id: "agent-security",
        name: "security",
        description: "Security audit and hardening specialist",
        systemPrompt:
          "You are an expert security engineer. Audit code for OWASP Top 10 vulnerabilities, insecure dependencies, " +
          "and improper secret handling. Recommend and implement hardening measures.",
        color: "red",
        allowedTools: ["read_file", "list_dir", "bash", "glob_find", "grep_search"],
        createdAt: now,
      },
      {
        id: "agent-docs",
        name: "docs",
        description: "Documentation and technical writing specialist",
        systemPrompt:
          "You are an expert technical writer. Write clear, concise, and accurate documentation. " +
          "Generate READMEs, API docs, changelogs, and inline code comments.",
        color: "blue",
        allowedTools: ["read_file", "write_file", "edit_file", "list_dir", "glob_find", "grep_search"],
        createdAt: now,
      },
    ];
    try {
      fs.mkdirSync(path.dirname(agentsConfigFile), { recursive: true });
      fs.writeFileSync(agentsConfigFile, JSON.stringify(defaultAgents, null, 2), "utf-8");
      console.log("  ✓ Pre-populated default specialist agents (~/.config/pakalon/agents.json)");
    } catch (agentErr) {
      debugLog(`[init] Could not write default agents: ${agentErr}`);
    }
  }
  debugLog(`[init] Initialized .pakalon/ in ${cwd} (AI=${useAI})`);
}

