/**
 * /pakalon command — trigger the full 6-phase agentic mode.
 * T123: Starts BridgeManager, opens AgentScreen with bridgeMode, handles HIL.
 */
import path from "path";
import fs from "fs";
import { debugLog } from "@/utils/logger.js";
import { startBridge, stopBridge } from "@/bridge/manager.js";
import { BRIDGE_PORT } from "@/bridge/types.js";

export interface AgentRunOptions {
  prompt: string;
  mode?: "hil" | "yolo";
  dir?: string;
  maxBudget?: number;
  userId?: string;
  userPlan?: string;
  figmaUrl?: string;
  targetUrl?: string;
}

/**
 * Prepare working directories for the agentic run.
 * Creates both .pakalon/ and .pakalon-agents/ in the target directory,
 * along with the full phase subdirectory tree required by all 6 pipeline phases.
 * T-CLI-P1: .pakalon-agents folder must be created alongside .pakalon.
 */
export function prepareAgentDirs(dir: string): void {
  const pakalonDir = path.join(dir, ".pakalon");
  const pakalonAgentsDir = path.join(dir, ".pakalon-agents");

  if (!fs.existsSync(pakalonDir)) {
    fs.mkdirSync(pakalonDir, { recursive: true });
    debugLog(`[pakalon] Created ${pakalonDir}`);
  }

  // Create default .pakalon/settings.json if missing
  const settingsFile = path.join(pakalonDir, "settings.json");
  if (!fs.existsSync(settingsFile)) {
    fs.writeFileSync(
      settingsFile,
      JSON.stringify({ version: 1, mode: "hil", privacyMode: false }, null, 2) + "\n",
    );
  }

  if (!fs.existsSync(pakalonAgentsDir)) {
    fs.mkdirSync(pakalonAgentsDir, { recursive: true });
    debugLog(`[pakalon] Created ${pakalonAgentsDir}`);
  }

  // Phase artifacts live under .pakalon-agents/ai-agents/ (matching Python paths.py)
  const aiAgentsDir = path.join(pakalonAgentsDir, "ai-agents");
  if (!fs.existsSync(aiAgentsDir)) {
    fs.mkdirSync(aiAgentsDir, { recursive: true });
    debugLog(`[pakalon] Created ${aiAgentsDir}`);
  }

  // ── sync.js reference ────────────────────────────────────────────────────
  // Place a launcher stub at .pakalon-agents/ai-agents/sync.js so the project
  // directory has a self-contained entry-point for the Penpot sync bridge.
  const syncStubPath = path.join(aiAgentsDir, "sync.js");
  if (!fs.existsSync(syncStubPath)) {
    fs.writeFileSync(
      syncStubPath,
      `#!/usr/bin/env node
/**
 * sync.js — Project-local Penpot Design Sync Bridge launcher.
 *
 * This stub re-exports and delegates to the CLI's canonical sync.js.
 * Run it directly:  node .pakalon-agents/ai-agents/sync.js --lifecycle
 */
const { execFileSync } = await import('child_process');
const { fileURLToPath } = await import('url');
const { join, dirname } = await import('path');

const __dir  = dirname(fileURLToPath(import.meta.url));
const cliDir = join(__dir, '..', '..', '..', 'pakalon-cli', 'python', 'agents', 'sync.js');

// Pass all CLI arguments through to the canonical sync.js
execFileSync(process.execPath, [cliDir, ...process.argv.slice(2)], {
  stdio : 'inherit',
  cwd   : join(__dir, '..', '..'),   // project root (where .pakalon-agents lives)
  env   : { ...process.env, PAKALON_AGENTS_DIR: join(__dir, '..', '..', '.pakalon-agents') },
});
`,
    );
    debugLog(`[pakalon] Created ${syncStubPath}`);
  }

  // ── Phase subdirs ─────────────────────────────────────────────────────────
  // Structure:
  //   phase-1/ ← plan, tasks, design, API_reference.md, Database_schema.md …
  //   phase-2/ ← wireframes, tdd-screenshots/
  //   phase-3/ ← subagent-1..5.md, execution_log.md, test-evidence/
  //   phase-4/ ← subagent-1..5.md, blackbox_testing.xml, whitebox_testing.xml
  //   phase-5/ ← CI/CD artifacts
  //   phase-6/ ← documentation
  const phaseDirs = [
    "phase-1",
    "phase-2",
    "phase-3",
    "phase-4",
    "phase-5",
    "phase-6",
  ];

  for (const sub of phaseDirs) {
    const subDir = path.join(aiAgentsDir, sub);
    if (!fs.existsSync(subDir)) {
      fs.mkdirSync(subDir, { recursive: true });
      debugLog(`[pakalon] Created ${subDir}`);
    }
    const gitkeep = path.join(subDir, ".gitkeep");
    if (!fs.existsSync(gitkeep)) {
      fs.writeFileSync(gitkeep, "");
    }
  }

  // ── Phase-1 placeholder files ─────────────────────────────────────────────
  // These are filled by the Phase-1 LangGraph agent; placeholders make the
  // structure immediately visible and hint to sub-agents where to write.
  const phase1Dir = path.join(aiAgentsDir, "phase-1");

  const apiReferencePath = path.join(phase1Dir, "API_reference.md");
  if (!fs.existsSync(apiReferencePath)) {
    fs.writeFileSync(
      apiReferencePath,
      `# API Reference\n\n> Generated by Phase-1 AI agent.\n>\n> This file documents all REST/GraphQL/WebSocket endpoints, request/response\n> schemas, authentication flows, and error codes for the project being built.\n>\n> Phase-3 Sub-agent 2 (Backend Framing) reads this file first and implements\n> the API layer exactly as documented here.\n\n## Endpoints\n\n_To be completed by Phase-1 agent based on planning output._\n`,
    );
    debugLog(`[pakalon] Created ${apiReferencePath}`);
  }

  const dbSchemaPath = path.join(phase1Dir, "Database_schema.md");
  if (!fs.existsSync(dbSchemaPath)) {
    fs.writeFileSync(
      dbSchemaPath,
      `# Database Schema\n\n> Generated by Phase-1 AI agent.\n>\n> This file contains the complete database design: entity-relationship model,\n> table definitions, column types, indexes, foreign keys, and seed data\n> for the technology chosen in Phase-1 planning.\n>\n> Phase-3 Sub-agent 2 (Backend Framing) reads this file and creates all\n> migrations/schema files from it.\n\n## Tables\n\n_To be completed by Phase-1 agent based on planning output._\n`,
    );
    debugLog(`[pakalon] Created ${dbSchemaPath}`);
  }

  // ── Phase-2 sub-directories ────────────────────────────────────────────────
  const phase2Dir = path.join(aiAgentsDir, "phase-2");
  const tddScreenshotsDir = path.join(phase2Dir, "tdd-screenshots");
  if (!fs.existsSync(tddScreenshotsDir)) {
    fs.mkdirSync(tddScreenshotsDir, { recursive: true });
    fs.writeFileSync(path.join(tddScreenshotsDir, ".gitkeep"), "");
    debugLog(`[pakalon] Created ${tddScreenshotsDir}`);
  }

  // ── Phase-3 extra files ────────────────────────────────────────────────────
  const phase3Dir = path.join(aiAgentsDir, "phase-3");

  const executionLogPath = path.join(phase3Dir, "execution_log.md");
  if (!fs.existsSync(executionLogPath)) {
    fs.writeFileSync(
      executionLogPath,
      `# Phase-3 Execution Log\n\n> Auto-generated log. Sub-agent 5 reads this to validate the full build.\n\n## Log Entries\n\n_Appended by each Phase-3 sub-agent as they execute._\n`,
    );
    debugLog(`[pakalon] Created ${executionLogPath}`);
  }

  const phase3TestEvidenceDir = path.join(phase3Dir, "test-evidence");
  if (!fs.existsSync(phase3TestEvidenceDir)) {
    fs.mkdirSync(phase3TestEvidenceDir, { recursive: true });
    fs.writeFileSync(path.join(phase3TestEvidenceDir, ".gitkeep"), "");
    debugLog(`[pakalon] Created ${phase3TestEvidenceDir}`);
  }

  // ── Phase-4 test XML stubs ─────────────────────────────────────────────────
  const phase4Dir = path.join(aiAgentsDir, "phase-4");

  const blackboxPath = path.join(phase4Dir, "blackbox_testing.xml");
  if (!fs.existsSync(blackboxPath)) {
    fs.writeFileSync(
      blackboxPath,
      `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Pakalon Phase-4 Black-Box Testing\n     Tests validate the application from the user's perspective (user stories).\n     Sub-agent 1 (SAST) populates this during Phase-4 execution. -->\n<blackbox-tests>\n  <!-- <test-suite name="Authentication">\n    <test id="BT-001" user-story="US-001">...\n  </test-suite> -->\n</blackbox-tests>\n`,
    );
    debugLog(`[pakalon] Created ${blackboxPath}`);
  }

  const whiteboxPath = path.join(phase4Dir, "whitebox_testing.xml");
  if (!fs.existsSync(whiteboxPath)) {
    fs.writeFileSync(
      whiteboxPath,
      `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Pakalon Phase-4 White-Box Testing\n     Tests examine internal structure, code paths, and architecture.\n     Sub-agent 3 (Code Review) populates this during Phase-4 execution. -->\n<whitebox-tests>\n  <!-- <test-suite name="Unit Tests">\n    <test id="WT-001" component="AuthService">...\n  </test-suite> -->\n</whitebox-tests>\n`,
    );
    debugLog(`[pakalon] Created ${whiteboxPath}`);
  }

  // Top-level support dirs stay directly under .pakalon-agents/
  const supportDirs = [
    "wireframes",    // Penpot / Figma wireframe exports
    "mcp-servers",   // Project-scoped MCP server configs
    "test-evidence", // Screenshots, HAR files, coverage reports
    "decisions",     // Cross-phase decision registry (trace)
  ];

  for (const sub of supportDirs) {
    const subDir = path.join(pakalonAgentsDir, sub);
    if (!fs.existsSync(subDir)) {
      fs.mkdirSync(subDir, { recursive: true });
      debugLog(`[pakalon] Created ${subDir}`);
    }
    const gitkeep = path.join(subDir, ".gitkeep");
    if (!fs.existsSync(gitkeep)) {
      fs.writeFileSync(gitkeep, "");
    }
  }

  // database file placeholder
  const dbPlaceholder = path.join(pakalonAgentsDir, "pakalon.db");
  if (!fs.existsSync(dbPlaceholder)) {
    fs.writeFileSync(dbPlaceholder, "");
  }

  // Write a README in .pakalon-agents to describe its purpose
  const agentsReadme = path.join(pakalonAgentsDir, "README.md");
  if (!fs.existsSync(agentsReadme)) {
    fs.writeFileSync(
      agentsReadme,
      `# .pakalon-agents\n\nThis directory contains all Pakalon agentic execution artifacts.\n\n` +
      `## Structure\n\n` +
      `\`\`\`\n` +
      `.pakalon-agents/\n` +
      `├── ai-agents/\n` +
      `│   ├── sync.js                   # Penpot sync bridge launcher (lifecycle owner)\n` +
      `│   ├── phase-1/\n` +
      `│   │   ├── plan.md               # Full project plan\n` +
      `│   │   ├── tasks.md              # Phase-split task list\n` +
      `│   │   ├── design.md             # UI/UX design brief\n` +
      `│   │   ├── API_reference.md      # ← used by Phase-3 SA-2 (backend)\n` +
      `│   │   ├── Database_schema.md    # ← used by Phase-3 SA-2 (backend)\n` +
      `│   │   ├── prd.md                # Product Requirements Document\n` +
      `│   │   ├── user-stories.md       # Acceptance-criteria user stories\n` +
      `│   │   ├── agent-skills.md       # Agent skill registry\n` +
      `│   │   ├── risk-assessment.md\n` +
      `│   │   ├── technical-spec.md\n` +
      `│   │   ├── competitive-analysis.md\n` +
      `│   │   ├── constraints-and-tradeoffs.md\n` +
      `│   │   ├── context_management.md\n` +
      `│   │   └── phase-1.md            # Consolidated phase summary\n` +
      `│   ├── phase-2/\n` +
      `│   │   ├── Wireframe_generated.svg\n` +
      `│   │   ├── Wireframe_generated.penpot\n` +
      `│   │   ├── phase-2.md\n` +
      `│   │   └── tdd-screenshots/      # TDD screenshot evidence\n` +
      `│   ├── phase-3/\n` +
      `│   │   ├── subagent-1.md  subagent-2.md  subagent-3.md\n` +
      `│   │   ├── subagent-4.md  subagent-5.md\n` +
      `│   │   ├── execution_log.md      # Full audit log (read by SA-5)\n` +
      `│   │   └── test-evidence/\n` +
      `│   ├── phase-4/\n` +
      `│   │   ├── subagent-1.md … subagent-5.md\n` +
      `│   │   ├── blackbox_testing.xml  # User-story perspective tests\n` +
      `│   │   └── whitebox_testing.xml  # Internal structure tests\n` +
      `│   ├── phase-5/\n` +
      `│   │   └── phase-5.md\n` +
      `│   └── phase-6/\n` +
      `│       └── phase-6.md\n` +
      `├── wireframes/    # Timestamped wireframe exports (SVG + .penpot)\n` +
      `├── mcp-servers/   # Project-scoped MCP server configs\n` +
      `├── test-evidence/ # Top-level test artefacts\n` +
      `├── decisions/     # Cross-phase decision registry\n` +
      `└── pakalon.db     # Local SQLite agent state\n` +
      `\`\`\`\n\n` +
      `## Penpot / Design Sync\n\n` +
      `Run the Penpot sync bridge from the project root:\n\n` +
      `\`\`\`bash\n` +
      `# Preferred: lifecycle mode (auto start/stop sync when Penpot opens/closes)\n` +
      `node .pakalon-agents/ai-agents/sync.js --lifecycle --file <penpot-file-id>\n\n` +
      `# Or via the CLI command:\n` +
      `pakalon /penpot\n` +
      `\`\`\`\n`,
    );
  }
}

/**
 * Launch the 6-phase agentic pipeline.
 * Returns config that can be used to render AgentScreen in bridge mode.
 */
export async function cmdPakalon(options: AgentRunOptions): Promise<{
  bridgePort: number;
  bridgeMode: {
    userPrompt: string;
    userId: string;
    userPlan: string;
    isYolo: boolean;
    figmaUrl?: string;
    targetUrl?: string;
  };
  projectDir: string;
}> {
  const {
    prompt,
    mode = "hil",
    dir = process.cwd(),
    userId = "anonymous",
    userPlan = "free",
    figmaUrl,
    targetUrl = "http://localhost:3000",
  } = options;

  console.log("\n✦ Starting Pakalon Agentic Mode...\n");

  if (mode === "yolo") {
    console.log("  Mode: YOLO (all phases auto-proceed, no human input required)");
  } else {
    console.log("  Mode: HIL (Human-in-the-Loop — you'll be asked before each phase)");
  }

  console.log(`  Working directory: ${dir}`);
  console.log(`  Prompt: "${prompt.slice(0, 80)}${prompt.length > 80 ? "..." : ""}"\n`);

  // Prepare .pakalon and .pakalon-agents directories (with all phase subdirs)
  prepareAgentDirs(dir);
  console.log("  ✓ Prepared .pakalon/ and .pakalon-agents/ai-agents/phase-{1..6}/ directories");

  // Start the Python bridge
  console.log("  Starting Python bridge...");
  let bridgePort: number;
  try {
    await startBridge();
    bridgePort = BRIDGE_PORT;
    console.log(`  ✓ Bridge ready on port ${bridgePort}`);
    debugLog(`[pakalon] Bridge started on port ${bridgePort}`);
  } catch (err) {
    console.error(`\n✗ Failed to start Python bridge: ${String(err)}`);
    console.error("  Make sure Python 3.12 is installed and bridge dependencies are available.");
    console.error("  Run: pakalon install\n");
    process.exit(1);
  }

  return {
    bridgePort,
    bridgeMode: {
      userPrompt: prompt,
      userId,
      userPlan,
      isYolo: mode === "yolo",
      figmaUrl,
      targetUrl,
    },
    projectDir: dir,
  };
}

/**
 * Get opening message for AgentScreen when /pakalon is invoked.
 */
export function getPakalonOpeningMessage(prompt: string, mode: string): string {
  return `Starting 6-phase agentic build for:

"${prompt}"

Mode: ${mode.toUpperCase()}

Phase 1 → Planning & Research
  - Web research for similar products
  - Q&A with you (HIL mode) or auto-proceed (YOLO mode)
  - Generating: plan.md, tasks.md, user-stories.md, design.md
  - Generating: API_reference.md ← Phase-3 SA-2 reads this
  - Generating: Database_schema.md ← Phase-3 SA-2 reads this
  - Plus 7 more planning docs

Phase 2 → Wireframe Generation
  - Penpot wireframe creation (auto-opens in browser)
  - sync.js lifecycle bridge (starts on open, stops on close)
  - Design review & iteration with TDD screenshots

Phase 3 → Development (5 specialist sub-agents)
  - SA-1: Frontend (uses wireframe from phase-2)
  - SA-2: Backend API (reads API_reference.md + Database_schema.md)
  - SA-3: Frontend ↔ Backend integration
  - SA-4: Debug, testing & chrome-devtools audit
  - SA-5: Feedback, review & execution_log.md

Phase 4 → Security QA (5 specialist sub-agents)
  - SAST + DAST scanning
  - blackbox_testing.xml + whitebox_testing.xml generated
  - Requirement verification

Phase 5 → CI/CD & Deployment
Phase 6 → Documentation

Starting now...`;
}
