/**
 * File Structure Template for Pakalon Agents
 * 
 * This module provides the complete .pakalon-agents/ folder structure
 * as defined in the requirements.
 * 
 * Structure:
 * {project-name}/
 * ├── .pakalon-agents/
 * │   ├── ai-agents/
 * │   │   ├── phase-1/
 * │   │   │   ├── context_management.md
 * │   │   │   ├── plan.md
 * │   │   │   ├── tasks.md
 * │   │   │   ├── design.md
 * │   │   │   ├── phase-1.md
 * │   │   │   ├── agent-skills.md
 * │   │   │   ├── prd.md
 * │   │   │   ├── Database_schema.md
 * │   │   │   ├── API_reference.md
 * │   │   │   ├── risk-assessment.md
 * │   │   │   ├── user-stories.md
 * │   │   │   ├── technical-spec.md
 * │   │   │   ├── competitive-analysis.md
 * │   │   │   └── constraints-and-tradeoffs.md
 * │   │   ├── phase-2/
 * │   │   │   ├── phase-2.md
 * │   │   │   ├── Wireframe_generated.svg
 * │   │   │   ├── Wireframe_generated.penpot
 * │   │   │   └── tdd-screenshots/
 * │   │   ├── phase-3/
 * │   │   │   ├── subagent-1.md
 * │   │   │   ├── subagent-2.md
 * │   │   │   ├── subagent-3.md
 * │   │   │   ├── subagent-4.md
 * │   │   │   ├── subagent-5.md
 * │   │   │   ├── execution_log.md
 * │   │   │   └── test-evidence/
 * │   │   ├── phase-4/
 * │   │   │   ├── subagent-1.md
 * │   │   │   ├── subagent-2.md
 * │   │   │   ├── subagent-3.md
 * │   │   │   ├── subagent-4.md
 * │   │   │   ├── subagent-5.md
 * │   │   │   ├── blackbox_testing.xml
 * │   │   │   └── whitebox_testing.xml
 * │   │   ├── phase-5/
 * │   │   │   └── phase-5.md
 * │   │   └── phase-6/
 * │   │       └── phase-6.md
 * │   ├── mcp-servers/
 * │   ├── wireframes/
 * │   └── pakalon.db
 * └── (visible project files - code, README, etc.)
 */

import fs from "fs";
import path from "path";

export interface PakalonAgentsConfig {
  projectDir: string;
  projectName: string;
}

/**
 * Get the complete folder structure as an array of paths
 */
export function getAgentsFolderStructure(config: PakalonAgentsConfig): string[] {
  const { projectDir, projectName } = config;
  const base = path.join(projectDir, ".pakalon-agents");
  
  return [
    // Main directories
    path.join(base, "ai-agents", "phase-1"),
    path.join(base, "ai-agents", "phase-2"),
    path.join(base, "ai-agents", "phase-3"),
    path.join(base, "ai-agents", "phase-4"),
    path.join(base, "ai-agents", "phase-5"),
    path.join(base, "ai-agents", "phase-6"),
    path.join(base, "mcp-servers"),
    path.join(base, "wireframes"),
    
    // Phase 2 subdirectories
    path.join(base, "ai-agents", "phase-2", "tdd-screenshots"),
    
    // Phase 3 subdirectories
    path.join(base, "ai-agents", "phase-3", "test-evidence"),
  ];
}

/**
 * Get all files with their initial content
 */
export function getAgentsFiles(config: PakalonAgentsConfig): Array<{ path: string; content: string }> {
  const { projectName } = config;
  const base = path.join(projectName, ".pakalon-agents");
  
  return [
    // Sync.js - Penpot lifecycle-aware sync bridge launcher (project-local stub)
    {
      path: path.join(base, "ai-agents", "sync.js"),
      content: `#!/usr/bin/env node
/**
 * sync.js — Project-local Penpot Design Sync Bridge launcher.
 *
 * LIFECYCLE CONTRACT:
 *   • sync.js is the SOLE controller for Penpot start / stop.
 *   • When Penpot opens  → sync.js starts the file-change poll loop.
 *   • When Penpot closes → sync.js stops the poll loop and exits.
 *   • Stopping sync.js (SIGTERM/SIGINT) also stops the Penpot container.
 *
 * COOLDOWN:
 *   After every successful sync a configurable cooldown window starts.
 *   During the cooldown no polls are sent → prevents excessive token usage.
 *
 * Run directly from the project root:
 *   node .pakalon-agents/ai-agents/sync.js --lifecycle --file <penpot-file-id>
 *   node .pakalon-agents/ai-agents/sync.js --start
 *   node .pakalon-agents/ai-agents/sync.js --stop
 *
 * This stub delegates to the CLI's canonical sync.js implementation.
 */
import { execFileSync } from 'child_process';
import { fileURLToPath } from 'url';
import { join, dirname } from 'path';

const __dir   = dirname(fileURLToPath(import.meta.url));
const cliSync = join(__dir, '..', '..', '..', 'pakalon-cli', 'python', 'agents', 'sync.js');

execFileSync(process.execPath, [cliSync, ...process.argv.slice(2)], {
  stdio : 'inherit',
  cwd   : join(__dir, '..', '..'),   // project root (where .pakalon-agents lives)
  env   : {
    ...process.env,
    PAKALON_AGENTS_DIR: join(__dir, '..', '..', '.pakalon-agents'),
  },
});
`
    },
    // Phase 1 files
    {
      path: path.join(base, "ai-agents", "phase-1", "plan.md"),
      content: `# Plan - ${projectName}

## Overview
_Generated by \`/pakalon\`. Edit this file with your project plan._

## Goals
- [ ] Define primary objective
- [ ] Identify key deliverables

## Architecture
_Describe your tech stack and high-level architecture here._

## Timeline
_Add milestones and deadlines._
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "tasks.md"),
      content: `# Tasks - ${projectName}

## Phase 1: Planning
- [ ] Complete requirements gathering
- [ ] Define tech stack
- [ ] Create initial plan

## Phase 2: Design
- [ ] Generate wireframes
- [ ] Get user approval

## Phase 3: Development
- [ ] Implement frontend
- [ ] Implement backend
- [ ] Integrate components

## Phase 4: Testing
- [ ] Run automated tests
- [ ] Fix bugs

## Phase 5: Deployment
- [ ] Deploy to production

## Phase 6: Documentation
- [ ] Generate README
- [ ] Create API docs
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "design.md"),
      content: `# Design - ${projectName}

## UI/UX Guidelines

### Color Palette
- Primary: #000000
- Secondary: #FFFFFF
- Accent: #3B82F6

### Typography
- Headings: Inter, sans-serif
- Body: Inter, sans-serif

### Layout
- Max width: 1280px
- Sidebar: 256px
- Content: Fluid

## Components

### Navigation
- Fixed header
- Collapsible sidebar

### Cards
- Rounded corners: 8px
- Shadow: subtle

### Buttons
- Primary: Filled
- Secondary: Outlined
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "context_management.md"),
      content: `# Context Management - ${projectName}

## Token Budget
- Total window: 200,000 tokens
- Phase allocation: 70% conversation, 30% tools

## Key Files (priority context loading order)
1. plan.md
2. tasks.md
3. design.md
4. Source files (most recently modified)
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "user-stories.md"),
      content: `# User Stories - ${projectName}

## US1 — Core User
**As a** user,
**I want to** ...
**So that** I can ...

**Acceptance Criteria:**
- [ ] AC1
- [ ] AC2

## US2 — Another User
**As a** admin,
**I want to** manage users
**So that** I can control access
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "prd.md"),
      content: `# Product Requirements Document - ${projectName}

## 1. Problem Statement
_Describe the problem this project solves_

## 2. Goals
- Primary goal 1
- Primary goal 2

## 3. User Personas
- Persona 1: Description
- Persona 2: Description

## 4. Functional Requirements
- FR-001: Description
- FR-002: Description

## 5. Non-Functional Requirements
- Performance: < 3s load time
- Security: HTTPS, encryption at rest
- Accessibility: WCAG 2.1 AA
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "risk-assessment.md"),
      content: `# Risk Assessment - ${projectName}

## Identified Risks

| Risk | Likelihood | Impact | Mitigation |
|------|------------|--------|------------|
| Risk 1 | Medium | High | Mitigation strategy |
| Risk 2 | Low | Medium | Mitigation strategy |

## Technical Risks
- Dependency on external APIs
- Performance at scale

## Mitigation Strategies
1. Strategy 1
2. Strategy 2
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "technical-spec.md"),
      content: `# Technical Specification - ${projectName}

## Architecture

### Frontend
- Framework: TBD (based on user input)
- Styling: Tailwind CSS

### Backend
- Framework: TBD
- Database: PostgreSQL

### Infrastructure
- Hosting: Vercel
- Database: Neon/Supabase
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "competitive-analysis.md"),
      content: `# Competitive Analysis - ${projectName}

## Competitors

| Competitor | Strengths | Weaknesses |
|------------|-----------|------------|
| Competitor A | Feature 1, Feature 2 | Limitation 1 |
| Competitor B | Feature 3 | Limitation 2 |

## Differentiation
- Key differentiator 1
- Key differentiator 2
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "constraints-and-tradeoffs.md"),
      content: `# Constraints and Trade-offs - ${projectName}

## Technical Constraints
- Budget: Limited
- Timeline: 3 months

## Trade-offs Made
1. Trade-off 1: Decision rationale
2. Trade-off 2: Decision rationale

## Future Considerations
- Scalability
- Maintainability
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "agent-skills.md"),
      content: `# Agent Skills - ${projectName}

## Available Skills

### Frontend Skills
- React development
- Tailwind CSS
- Responsive design

### Backend Skills
- REST API design
- Database design
- Authentication

### DevOps Skills
- Docker
- CI/CD
- Deployment
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "API_reference.md"),
      content: `# API Reference - ${projectName}

> Generated by Pakalon Phase 1

## Overview
_Complete API documentation will be generated based on the plan and tasks._

## Base URL
\`\`\`
Development: http://localhost:8000/api/v1
Production: https://api.example.com/api/v1
\`\`\`
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "Database_schema.md"),
      content: `# Database Schema - ${projectName}

> Generated by Pakalon Phase 1

## Overview
_Database schema will be generated based on the plan and tasks._

## Tables
- users
- sessions
- (more to be added based on requirements)
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-1", "phase-1.md"),
      content: `# Phase 1: Planning & Requirements

## Summary
This phase covers all planning and requirements gathering.

## Files Generated
- plan.md
- tasks.md
- design.md
- context_management.md
- user-stories.md
- prd.md
- risk-assessment.md
- technical-spec.md
- competitive-analysis.md
- constraints-and-tradeoffs.md
- agent-skills.md
- API_reference.md
- Database_schema.md

## Status: COMPLETED
`,
    },
    
    // Phase 2 files
    {
      path: path.join(base, "ai-agents", "phase-2", "phase-2.md"),
      content: `# Phase 2: Wireframe Generation

## Summary
This phase generates wireframes based on the design.md from Phase 1.

## Files Generated
- Wireframe_generated.svg
- Wireframe_generated.penpot
- tdd-screenshots/

## Status: PENDING
`,
    },
    
    // Phase 3 files
    {
      path: path.join(base, "ai-agents", "phase-3", "auditor.md"),
      content: `# Auditor Report

## Summary
The Auditor agent scans the codebase against requirements.

## Status: PENDING

## Usage
- \`/auditor\` - Run auditor
`,
    },
  {
      path: path.join(base, "ai-agents", "phase-3", "subagent-1.md"),
      content: `# Phase 3 - Subagent 1: Frontend Development

## Summary
Frontend implementation based on wireframes from Phase 2.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-3", "subagent-2.md"),
      content: `# Phase 3 - Subagent 2: Backend Development

## Summary
Backend implementation using API_reference.md and Database_schema.md.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-3", "subagent-3.md"),
      content: `# Phase 3 - Subagent 3: Integration

## Summary
Frontend and backend integration.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-3", "subagent-4.md"),
      content: `# Phase 3 - Subagent 4: Testing & Debugging

## Summary
Testing and bug fixing.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-3", "subagent-5.md"),
      content: `# Phase 3 - Subagent 5: User Feedback

## Summary
User feedback collection and documentation.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-3", "execution_log.md"),
      content: `# Phase 3 Execution Log

## Activities
_Log of all activities performed in Phase 3_
`,
    },
    
    // Phase 4 files
    {
      path: path.join(base, "ai-agents", "phase-4", "phase-4.md"),
      content: `# Phase 4: Testing & Quality Assurance

## Summary
Comprehensive testing including SAST, DAST, and manual review.

## Status: PENDING
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-4", "blackbox_testing.xml"),
      content: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Pakalon Phase-4 Black-Box Testing
     Tests validate the application from the user's perspective (user stories).
     Sub-agent 1 (SAST) populates this during Phase-4 execution. -->
<blackbox-tests>
  <!-- <test-suite name="Authentication">
    <test id="BT-001" user-story="US-001">
      <description>User can register with valid credentials</description>
      <steps>
        <step>Navigate to /register</step>
        <step>Fill in email and password</step>
        <step>Submit form</step>
      </steps>
      <expected-result>User is redirected to dashboard</expected-result>
    </test>
  </test-suite> -->
</blackbox-tests>
`,
    },
    {
      path: path.join(base, "ai-agents", "phase-4", "whitebox_testing.xml"),
      content: `<?xml version="1.0" encoding="UTF-8"?>
<!-- Pakalon Phase-4 White-Box Testing
     Tests examine internal structure, code paths, and architecture.
     Sub-agent 3 (Code Review) populates this during Phase-4 execution. -->
<whitebox-tests>
  <!-- <test-suite name="Unit Tests">
    <test id="WT-001" component="AuthService" method="registerUser">
      <description>registerUser hashes password before saving</description>
      <assertions>
        <assertion>bcrypt.hash is called with raw password</assertion>
        <assertion>DB insert uses hashed password, not plain text</assertion>
      </assertions>
    </test>
  </test-suite>
  <test-suite name="Integration Tests">
    <test id="WT-010" component="AuthController → AuthService → DB">
      <description>POST /api/auth/register creates user in DB</description>
    </test>
  </test-suite> -->
</whitebox-tests>
`,
    },
    
    // Phase 5 files
    {
      path: path.join(base, "ai-agents", "phase-5", "phase-5.md"),
      content: `# Phase 5: Deployment

## Summary
Deployment to production environment.

## Status: PENDING
`,
    },
    
    // Phase 6 files
    {
      path: path.join(base, "ai-agents", "phase-6", "phase-6.md"),
      content: `# Phase 6: Documentation

## Summary
Final documentation and handover.

## Status: PENDING
`,
    },
  ];
}

/**
 * Create the complete .pakalon-agents folder structure
 */
export function createAgentsFolderStructure(config: PakalonAgentsConfig): void {
  const files = getAgentsFiles(config);
  
  for (const file of files) {
    const dir = path.dirname(file.path);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    if (!fs.existsSync(file.path)) {
      fs.writeFileSync(file.path, file.content);
    }
  }
  
  console.log(`[init] Created .pakalon-agents folder structure at: ${config.projectDir}`);
}

export default {
  getAgentsFolderStructure,
  getAgentsFiles,
  createAgentsFolderStructure,
};
