"""
API Reference Generator - Generates API_reference.md for Phase 1

This module creates a comprehensive API reference document based on the
plan.md and tasks.md files created during Phase 1 planning.

The generated API_reference.md includes:
- All API endpoints with HTTP methods
- Request/response schemas
- Authentication requirements
- Error handling
- Code examples in multiple languages

Used by Phase 3 subagent-2 for backend development.
"""

from typing import Any


def generate_api_reference(
    plan_content: str,
    tasks_content: str,
    project_name: str = "Project",
    backend_framework: str = "FastAPI",
    database: str = "PostgreSQL",
) -> str:
    """
    Generate a comprehensive API reference document.

    Args:
        plan_content: Content of plan.md
        tasks_content: Content of tasks.md
        project_name: Name of the project
        backend_framework: Backend framework (FastAPI, Express, Django, etc.)
        database: Database type (PostgreSQL, MongoDB, etc.)

    Returns:
        Markdown-formatted API reference document
    """

    # Extract key information from plan and tasks
    features = _extract_features(plan_content, tasks_content)
    auth_requirements = _extract_auth_requirements(plan_content)

    # Generate API endpoints based on features
    endpoints = _generate_endpoints(features, auth_requirements)

    # Build the document
    doc = f"""# API Reference - {project_name}

> Generated by Pakalon Phase 1
> Framework: {backend_framework}
> Database: {database}

## Table of Contents

1. [Overview](#overview)
2. [Authentication](#authentication)
3. [API Endpoints](#api-endpoints)
4. [Data Models](#data-models)
5. [Error Handling](#error-handling)
6. [Code Examples](#code-examples)

---

## Overview

This document provides a complete API reference for **{project_name}**.

### Base URL

```
Development: http://localhost:8000/api/v1
Production: https://api.{project_name.lower().replace(" ", "")}.com/api/v1
```

### Content Type

All API requests and responses use JSON format:

```
Content-Type: application/json
```

---

## Authentication

{_generate_auth_section(auth_requirements)}

---

## API Endpoints

### Authentication Endpoints

| Method | Endpoint | Description |
|--------|----------|-------------|
| POST | /auth/register | Register a new user |
| POST | /auth/login | Login and get access token |
| POST | /auth/refresh | Refresh access token |
| POST | /auth/logout | Logout and invalidate token |
| POST | /auth/forgot-password | Request password reset |
| POST | /auth/reset-password | Reset password with token |

{endpoints}

---

## Data Models

### User

```json
{{
  "id": "uuid",
  "email": "string",
  "username": "string",
  "created_at": "datetime",
  "updated_at": "datetime",
  "is_active": "boolean"
}}
```

### Common Response Envelopes

**Success Response:**
```json
{{
  "success": true,
  "data": {{ ... }},
  "message": "Operation successful"
}}
```

**Error Response:**
```json
{{
  "success": false,
  "error": {{
    "code": "ERROR_CODE",
    "message": "Human readable message"
  }}
}}
```

---

## Error Handling

All errors follow a consistent format:

| Status Code | Description |
|------------|-------------|
| 400 | Bad Request - Invalid parameters |
| 401 | Unauthorized - Invalid or missing auth |
| 403 | Forbidden - Insufficient permissions |
| 404 | Not Found - Resource doesn't exist |
| 409 | Conflict - Resource already exists |
| 422 | Validation Error - Invalid data format |
| 500 | Internal Server Error |

### Error Codes

| Code | Description |
|------|-------------|
| AUTH_INVALID_CREDENTIALS | Invalid email or password |
| AUTH_TOKEN_EXPIRED | JWT token has expired |
| AUTH_INSUFFICIENT_PERMISSIONS | User lacks required permissions |
| VALIDATION_ERROR | Request validation failed |
| RESOURCE_NOT_FOUND | Requested resource doesn't exist |

---

## Code Examples

### JavaScript/TypeScript

```javascript
// Fetch user profile
const response = await fetch('/api/v1/users/me', {{
  headers: {{
    'Authorization': `Bearer ${{accessToken}}`,
    'Content-Type': 'application/json'
  }}
}});

const user = await response.json();
console.log(user);
```

### Python

```python
import requests

# Fetch user profile
response = requests.get(
    '/api/v1/users/me',
    headers={{
        'Authorization': f'Bearer {{access_token}}',
        'Content-Type': 'application/json'
    }}
)

user = response.json()
print(user)
```

### cURL

```bash
# Fetch user profile
curl -X GET http://localhost:8000/api/v1/users/me \\
  -H "Authorization: Bearer <token>" \\
  -H "Content-Type: application/json"
```

---

## Rate Limiting

API endpoints are rate-limited to ensure fair usage:

| Endpoint | Limit |
|----------|-------|
| /auth/* | 10 requests/minute |
| /api/* | 100 requests/minute |
| /webhooks/* | 200 requests/minute |

Rate limit headers are included in responses:
- `X-RateLimit-Limit`: Maximum requests per window
- `X-RateLimit-Remaining`: Remaining requests in window
- `X-RateLimit-Reset`: Unix timestamp when limit resets

---

## Versioning

The API uses URL-based versioning:

```
/api/v1/users
/api/v2/users
```

### Versioning Policy

- Major version changes introduce breaking changes
- Minor version changes add new features (backward compatible)
- Patch versions fix bugs (backward compatible)

---

Generated by Pakalon AI Agent - Phase 1
"""

    return doc


def _extract_features(plan_content: str, tasks_content: str) -> list[dict[str, str]]:
    """Extract features from plan and tasks content."""
    features = []

    # Common feature patterns
    feature_patterns = [
        {"name": "Users", "endpoint": "users", "methods": ["GET", "POST"]},
        {"name": "Authentication", "endpoint": "auth", "methods": ["POST"]},
        {
            "name": "Products",
            "endpoint": "products",
            "methods": ["GET", "POST", "PUT", "DELETE"],
        },
        {"name": "Orders", "endpoint": "orders", "methods": ["GET", "POST", "PUT"]},
        {"name": "Payments", "endpoint": "payments", "methods": ["GET", "POST"]},
        {"name": "Categories", "endpoint": "categories", "methods": ["GET", "POST"]},
        {"name": "Search", "endpoint": "search", "methods": ["GET"]},
        {"name": "Uploads", "endpoint": "uploads", "methods": ["POST"]},
    ]

    plan_lower = plan_content.lower()
    tasks_lower = tasks_content.lower()

    for feature in feature_patterns:
        if (
            feature["name"].lower() in plan_lower
            or feature["name"].lower() in tasks_lower
        ):
            features.append(feature)

    # Always include basic user endpoints
    if not any(f["endpoint"] == "users" for f in features):
        features.insert(
            0, {"name": "Users", "endpoint": "users", "methods": ["GET", "POST"]}
        )

    return features


def _extract_auth_requirements(plan_content: str) -> dict[str, Any]:
    """Extract authentication requirements from plan."""
    plan_lower = plan_content.lower()

    return {
        "jwt": "jwt" in plan_lower or "token" in plan_lower,
        "oauth": "oauth" in plan_lower or "social" in plan_lower,
        "roles": "role" in plan_lower or "permission" in plan_lower,
        "email_verification": "verify" in plan_lower and "email" in plan_lower,
    }


def _generate_endpoints(features: list[dict[str, str]], auth_requirements: dict) -> str:
    """Generate API endpoint documentation."""

    endpoint_docs = []

    for feature in features:
        name = feature["name"]
        endpoint = feature["endpoint"]
        methods = feature["methods"]

        # Generate CRUD endpoints
        if "GET" in methods:
            endpoint_docs.append(f"""
### {name} - List

| Method | Endpoint | Description |
|--------|----------|-------------|
| GET | /{endpoint} | List all {name.lower()} |
| GET | /{{id}} | Get single {name.lower()} by ID |
""")

        if "POST" in methods:
            endpoint_docs.append(f"""
### {name} - Create

| Method | Endpoint | Description |
|--------|----------|-------------|
| POST | /{endpoint} | Create new {name.lower()} |
""")

        if "PUT" in methods:
            endpoint_docs.append(f"""
### {name} - Update

| Method | Endpoint | Description |
|--------|----------|-------------|
| PUT | /{{id}} | Update {name.lower()} |
| PATCH | /{{id}} | Partial update {name.lower()} |
""")

        if "DELETE" in methods:
            endpoint_docs.append(f"""
### {name} - Delete

| Method | Endpoint | Description |
|--------|----------|-------------|
| DELETE | /{{id}} | Delete {name.lower()} |
""")

    return "\n".join(endpoint_docs)


def _generate_auth_section(auth_requirements: dict) -> str:
    """Generate authentication section."""

    sections = []

    if auth_requirements.get("jwt"):
        sections.append("""
### JWT Authentication

The API uses JWT (JSON Web Tokens) for authentication.

1. **Login** to receive access and refresh tokens
2. **Include** the access token in the Authorization header
3. **Refresh** the token before it expires

#### Headers

```
Authorization: Bearer <access_token>
```
""")

    if auth_requirements.get("oauth"):
        sections.append("""
### OAuth 2.0

Supported OAuth providers:
- GitHub
- Google

Use the `/auth/oauth/{provider}` endpoint to initiate OAuth flow.
""")

    if auth_requirements.get("roles"):
        sections.append("""
### Role-Based Access Control

Roles:
- `admin`: Full access to all resources
- `user`: Access to own resources
- `guest`: Read-only access

Check `user.role` to determine permissions.
""")

    if not sections:
        sections.append("""
### No Authentication

These endpoints are publicly accessible:
- GET /health
- GET /api/v1/public/*
""")

    return "\n".join(sections)
