"""
Database Schema Generator - Generates Database_schema.md for Phase 1

This module creates a comprehensive database schema document based on the
plan.md and tasks.md files created during Phase 1 planning.

The generated Database_schema.md includes:
- Complete database schema with all tables
- Column definitions with types and constraints
- Relationships between tables
- Indexes and constraints
- SQLAlchemy models (optional)
- Migration scripts (optional)

Used by Phase 3 subagent-2 for backend development.
"""

from typing import Any
from datetime import datetime


def generate_database_schema(
    plan_content: str,
    tasks_content: str,
    project_name: str = "Project",
    database_type: str = "PostgreSQL",
) -> str:
    """
    Generate a comprehensive database schema document.

    Args:
        plan_content: Content of plan.md
        tasks_content: Content of tasks.md
        project_name: Name of the project
        database_type: Database type (PostgreSQL, MySQL, MongoDB, etc.)

    Returns:
        Markdown-formatted database schema document
    """

    # Extract tables from plan and tasks
    tables = _extract_tables(plan_content, tasks_content)

    # Build the document
    doc = f"""# Database Schema - {project_name}

> Generated by Pakalon Phase 1
> Database: {database_type}
> Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Table of Contents

1. [Overview](#overview)
2. [Entity Relationship Diagram](#entity-relationship-diagram)
3. [Tables](#tables)
4. [Indexes](#indexes)
5. [Relationships](#relationships)
6. [SQLAlchemy Models](#sqlalchemy-models)
7. [Migration Scripts](#migration-scripts)

---

## Overview

This document provides the complete database schema for **{project_name}**.

### Database Information

| Property | Value |
|----------|-------|
| Database Type | {database_type} |
| Encoding | UTF-8 |
| Timezone | UTC |

---

## Entity Relationship Diagram

```
{_generate_erd(tables)}
```

---

## Tables

"""

    # Add each table
    for table in tables:
        doc += f"""
### {table["name"]}

{table.get("description", f"{table['name']} table")}

| Column | Type | Constraints | Description |
|--------|------|-------------|-------------|
"""

        for col in table.get("columns", []):
            constraints = []
            if col.get("primary_key"):
                constraints.append("PRIMARY KEY")
            if col.get("unique"):
                constraints.append("UNIQUE")
            if not col.get("nullable", True):
                constraints.append("NOT NULL")
            if col.get("default"):
                constraints.append(f"DEFAULT {col['default']}")
            if col.get("foreign_key"):
                constraints.append(f"REFERENCES {col['foreign_key']}")

            constraints_str = ", ".join(constraints) if constraints else "-"

            doc += f"| {col['name']} | {col['type']} | {constraints_str} | {col.get('description', '')} |\n"

        # Add sample data section
        if table.get("sample_data"):
            doc += f"""
#### Sample Data

```
{table["sample_data"]}
```
"""

    # Add indexes section
    doc += "\n## Indexes\n\n"
    doc += "| Table | Index Name | Columns | Type |\n"
    doc += "|-------|------------|---------|------|\n"

    for table in tables:
        for idx in table.get("indexes", []):
            doc += f"| {table['name']} | {idx['name']} | {idx['columns']} | {idx.get('type', 'BTREE')} |\n"

    # Add relationships section
    doc += "\n## Relationships\n\n"
    doc += "| From | To | Type | Description |\n"
    doc += "|------|-----|------|-------------|\n"

    for table in tables:
        for rel in table.get("relationships", []):
            doc += f"| {table['name']} | {rel['target']} | {rel['type']} | {rel.get('description', '')} |\n"

    # Add SQLAlchemy models
    doc += "\n## SQLAlchemy Models\n\n"
    doc += "```python\n"
    doc += _generate_sqlalchemy_models(tables, database_type)
    doc += "\n```\n"

    # Add migration script
    doc += "\n## Migration Scripts\n\n"
    doc += f"### Create All Tables ({database_type})\n\n"
    doc += "```sql\n"
    doc += _generate_migration_sql(tables, database_type)
    doc += "\n```\n"

    doc += f"""

---

Generated by Pakalon AI Agent - Phase 1
"""

    return doc


def _extract_tables(plan_content: str, tasks_content: str) -> list[dict[str, Any]]:
    """Extract database tables from plan and tasks content."""

    tables = []

    # Common table patterns
    table_patterns = [
        {
            "name": "users",
            "description": "User accounts and authentication",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "email",
                    "type": "VARCHAR(255)",
                    "unique": True,
                    "nullable": False,
                    "description": "User email address",
                },
                {
                    "name": "username",
                    "type": "VARCHAR(100)",
                    "unique": True,
                    "nullable": False,
                    "description": "Username",
                },
                {
                    "name": "password_hash",
                    "type": "VARCHAR(255)",
                    "nullable": False,
                    "description": "Bcrypt hashed password",
                },
                {
                    "name": "full_name",
                    "type": "VARCHAR(255)",
                    "description": "Full name",
                },
                {
                    "name": "avatar_url",
                    "type": "TEXT",
                    "nullable": True,
                    "description": "Profile picture URL",
                },
                {
                    "name": "role",
                    "type": "VARCHAR(50)",
                    "default": "'user'",
                    "description": "User role",
                },
                {
                    "name": "is_active",
                    "type": "BOOLEAN",
                    "default": "TRUE",
                    "description": "Account active status",
                },
                {
                    "name": "email_verified",
                    "type": "BOOLEAN",
                    "default": "FALSE",
                    "description": "Email verified",
                },
                {
                    "name": "created_at",
                    "type": "TIMESTAMP",
                    "default": "CURRENT_TIMESTAMP",
                    "description": "Creation timestamp",
                },
                {
                    "name": "updated_at",
                    "type": "TIMESTAMP",
                    "description": "Last update timestamp",
                },
            ],
            "indexes": [
                {"name": "idx_users_email", "columns": "email"},
                {"name": "idx_users_username", "columns": "username"},
            ],
            "relationships": [
                {
                    "target": "sessions",
                    "type": "one-to-many",
                    "description": "User sessions",
                },
                {
                    "target": "orders",
                    "type": "one-to-many",
                    "description": "User orders",
                },
            ],
            "sample_data": "INSERT INTO users (id, email, username, password_hash) VALUES ...",
        },
        {
            "name": "sessions",
            "description": "User authentication sessions",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "user_id",
                    "type": "UUID",
                    "nullable": False,
                    "foreign_key": "users(id)",
                    "description": "Foreign key to users",
                },
                {
                    "name": "access_token",
                    "type": "TEXT",
                    "description": "JWT access token",
                },
                {
                    "name": "refresh_token",
                    "type": "TEXT",
                    "description": "JWT refresh token",
                },
                {
                    "name": "expires_at",
                    "type": "TIMESTAMP",
                    "description": "Token expiration",
                },
                {
                    "name": "ip_address",
                    "type": "VARCHAR(45)",
                    "description": "IP address",
                },
                {
                    "name": "user_agent",
                    "type": "TEXT",
                    "description": "Browser/User agent",
                },
                {
                    "name": "created_at",
                    "type": "TIMESTAMP",
                    "default": "CURRENT_TIMESTAMP",
                    "description": "Creation timestamp",
                },
            ],
            "indexes": [
                {"name": "idx_sessions_user_id", "columns": "user_id"},
                {"name": "idx_sessions_access_token", "columns": "access_token"},
            ],
            "relationships": [
                {
                    "target": "users",
                    "type": "many-to-one",
                    "description": "User owning session",
                },
            ],
        },
        {
            "name": "products",
            "description": "Product catalog",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "name",
                    "type": "VARCHAR(255)",
                    "nullable": False,
                    "description": "Product name",
                },
                {
                    "name": "slug",
                    "type": "VARCHAR(255)",
                    "unique": True,
                    "nullable": False,
                    "description": "URL slug",
                },
                {
                    "name": "description",
                    "type": "TEXT",
                    "description": "Product description",
                },
                {
                    "name": "price",
                    "type": "DECIMAL(10,2)",
                    "nullable": False,
                    "description": "Product price",
                },
                {
                    "name": "stock",
                    "type": "INTEGER",
                    "default": "0",
                    "description": "Stock quantity",
                },
                {
                    "name": "category_id",
                    "type": "UUID",
                    "foreign_key": "categories(id)",
                    "description": "Category",
                },
                {"name": "image_url", "type": "TEXT", "description": "Product image"},
                {
                    "name": "is_active",
                    "type": "BOOLEAN",
                    "default": "TRUE",
                    "description": "Active status",
                },
                {
                    "name": "created_at",
                    "type": "TIMESTAMP",
                    "default": "CURRENT_TIMESTAMP",
                    "description": "Creation timestamp",
                },
                {
                    "name": "updated_at",
                    "type": "TIMESTAMP",
                    "description": "Last update",
                },
            ],
            "indexes": [
                {"name": "idx_products_slug", "columns": "slug"},
                {"name": "idx_products_category_id", "columns": "category_id"},
            ],
            "relationships": [
                {
                    "target": "categories",
                    "type": "many-to-one",
                    "description": "Product category",
                },
                {
                    "target": "order_items",
                    "type": "one-to-many",
                    "description": "Order items",
                },
            ],
        },
        {
            "name": "categories",
            "description": "Product categories",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "name",
                    "type": "VARCHAR(100)",
                    "unique": True,
                    "nullable": False,
                    "description": "Category name",
                },
                {
                    "name": "slug",
                    "type": "VARCHAR(100)",
                    "unique": True,
                    "nullable": False,
                    "description": "URL slug",
                },
                {
                    "name": "description",
                    "type": "TEXT",
                    "description": "Category description",
                },
                {
                    "name": "parent_id",
                    "type": "UUID",
                    "foreign_key": "categories(id)",
                    "description": "Parent category",
                },
                {
                    "name": "created_at",
                    "type": "TIMESTAMP",
                    "default": "CURRENT_TIMESTAMP",
                    "description": "Creation timestamp",
                },
            ],
            "indexes": [
                {"name": "idx_categories_slug", "columns": "slug"},
                {"name": "idx_categories_parent_id", "columns": "parent_id"},
            ],
            "relationships": [
                {
                    "target": "products",
                    "type": "one-to-many",
                    "description": "Products in category",
                },
                {
                    "target": "categories",
                    "type": "self-referential",
                    "description": "Subcategories",
                },
            ],
        },
        {
            "name": "orders",
            "description": "Customer orders",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "user_id",
                    "type": "UUID",
                    "nullable": False,
                    "foreign_key": "users(id)",
                    "description": "Foreign key to users",
                },
                {
                    "name": "order_number",
                    "type": "VARCHAR(50)",
                    "unique": True,
                    "nullable": False,
                    "description": "Order number",
                },
                {
                    "name": "status",
                    "type": "VARCHAR(50)",
                    "default": "'pending'",
                    "description": "Order status",
                },
                {
                    "name": "total_amount",
                    "type": "DECIMAL(10,2)",
                    "nullable": False,
                    "description": "Total order amount",
                },
                {
                    "name": "shipping_address",
                    "type": "JSONB",
                    "description": "Shipping address",
                },
                {"name": "notes", "type": "TEXT", "description": "Order notes"},
                {
                    "name": "created_at",
                    "type": "TIMESTAMP",
                    "default": "CURRENT_TIMESTAMP",
                    "description": "Creation timestamp",
                },
                {
                    "name": "updated_at",
                    "type": "TIMESTAMP",
                    "description": "Last update",
                },
            ],
            "indexes": [
                {"name": "idx_orders_user_id", "columns": "user_id"},
                {"name": "idx_orders_order_number", "columns": "order_number"},
                {"name": "idx_orders_status", "columns": "status"},
            ],
            "relationships": [
                {"target": "users", "type": "many-to-one", "description": "Customer"},
                {
                    "target": "order_items",
                    "type": "one-to-many",
                    "description": "Order items",
                },
            ],
        },
        {
            "name": "order_items",
            "description": "Order line items",
            "columns": [
                {
                    "name": "id",
                    "type": "UUID",
                    "primary_key": True,
                    "description": "Primary key",
                },
                {
                    "name": "order_id",
                    "type": "UUID",
                    "nullable": False,
                    "foreign_key": "orders(id)",
                    "description": "Foreign key to orders",
                },
                {
                    "name": "product_id",
                    "type": "UUID",
                    "nullable": False,
                    "foreign_key": "products(id)",
                    "description": "Foreign key to products",
                },
                {
                    "name": "quantity",
                    "type": "INTEGER",
                    "nullable": False,
                    "description": "Quantity",
                },
                {
                    "name": "unit_price",
                    "type": "DECIMAL(10,2)",
                    "nullable": False,
                    "description": "Unit price at time of order",
                },
                {
                    "name": "subtotal",
                    "type": "DECIMAL(10,2)",
                    "nullable": False,
                    "description": "Subtotal",
                },
            ],
            "indexes": [
                {"name": "idx_order_items_order_id", "columns": "order_id"},
                {"name": "idx_order_items_product_id", "columns": "product_id"},
            ],
            "relationships": [
                {"target": "orders", "type": "many-to-one", "description": "Order"},
                {"target": "products", "type": "many-to-one", "description": "Product"},
            ],
        },
    ]

    plan_lower = plan_content.lower()
    tasks_lower = tasks_content.lower()

    # Add tables based on what was found in plan/tasks
    for table in table_patterns:
        table_name = table["name"].lower()
        if table_name in plan_lower or table_name in tasks_lower:
            tables.append(table)

    # Always include users table
    if not any(t["name"] == "users" for t in tables):
        tables.insert(0, table_patterns[0])

    return tables


def _generate_erd(tables: list[dict]) -> str:
    """Generate a simple ASCII ERD."""

    lines = []

    for table in tables:
        lines.append(f"  {table['name']}")
        for col in table.get("columns", [])[:4]:  # Show first 4 columns
            pk = "PK" if col.get("primary_key") else "  "
            fk = "FK" if col.get("foreign_key") else "  "
            lines.append(f"    {pk} {fk} {col['name']} : {col['type']}")
        lines.append("")

        # Show relationships
        for rel in table.get("relationships", []):
            if rel["type"] == "one-to-many":
                lines.append(f"  1--* {rel['target']}")
            elif rel["type"] == "many-to-one":
                lines.append(f"  *--1 {table['name']}")

    return "\n".join(lines[:30])  # Limit lines


def _generate_sqlalchemy_models(tables: list[dict], database_type: str) -> str:
    """Generate SQLAlchemy model definitions."""

    code = """from sqlalchemy import Column, String, Text, Integer, Numeric, Boolean, DateTime, ForeignKey, JSON
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.sql import func

from app.database import Base


"""

    for table in tables:
        class_name = "".join(word.capitalize() for word in table["name"].split("_"))

        code += f"class {class_name}(Base):\n"
        code += f'    __tablename__ = "{table["name"]}"\n\n'

        # Add columns
        for col in table["columns"]:
            col_def = f"    {col['name']} = Column("

            # Map types
            if col["type"].startswith("UUID"):
                col_def += "UUID(as_uuid=True), "
            elif col["type"].startswith("VARCHAR"):
                max_len = (
                    col["type"].split("(")[1].split(")")[0]
                    if "(" in col["type"]
                    else "255"
                )
                col_def += f"String({max_len}), "
            elif col["type"].startswith("TEXT"):
                col_def += "Text, "
            elif col["type"].startswith("INTEGER"):
                col_def += "Integer, "
            elif col["type"].startswith("DECIMAL"):
                col_def += "Numeric(10, 2), "
            elif col["type"].startswith("BOOLEAN"):
                col_def += "Boolean, "
            elif col["type"].startswith("TIMESTAMP"):
                col_def += "DateTime, "
            elif col["type"].startswith("JSONB"):
                col_def += "JSON, "

            # Add constraints
            if col.get("primary_key"):
                col_def += "primary_key=True, "
            if not col.get("nullable", True):
                col_def += "nullable=False, "
            if col.get("unique"):
                col_def += "unique=True, "
            if col.get("default"):
                col_def += f"default={col['default']}, "
            if col.get("foreign_key"):
                fk = col["foreign_key"]
                col_def += f"ForeignKey('{fk}'), "

            col_def = col_def.rstrip(", ") + ")\n"
            code += col_def

        # Add relationships
        for rel in table.get("relationships", []):
            if rel["type"] == "one-to-many":
                target_class = "".join(
                    word.capitalize() for word in rel["target"].split("_")
                )
                code += f"\n    {rel['target']} = relationship('{target_class}', back_populators='{table['name']}')"

        code += "\n\n"

    return code


def _generate_migration_sql(tables: list[dict], database_type: str) -> str:
    """Generate SQL migration script."""

    sql = f"-- Database Migration: {database_type}\n"
    sql += f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

    for table in tables:
        sql += f"-- Table: {table['name']}\n"
        sql += f"CREATE TABLE {table['name']} (\n"

        col_defs = []
        for col in table["columns"]:
            col_def = f"    {col['name']} {col['type']}"

            if col.get("primary_key"):
                col_def += " PRIMARY KEY"
            if not col.get("nullable", True):
                col_def += " NOT NULL"
            if col.get("unique"):
                col_def += " UNIQUE"
            if col.get("default"):
                col_def += f" DEFAULT {col['default']}"
            if col.get("foreign_key"):
                col_def += f" REFERENCES {col['foreign_key']}"

            col_defs.append(col_def)

        sql += ",\n".join(col_defs)
        sql += "\n);\n"

        # Add indexes
        for idx in table.get("indexes", []):
            sql += (
                f"CREATE INDEX {idx['name']} ON {table['name']} ({idx['columns']});\n"
            )

        sql += "\n"

    return sql
